### ISSUE TITLE
Refresh Access Token gives back internal server error.

### ISSUE THREAD

**Issue by Liscuri** [swiftyspiffy/twitch-token-generator#18] opened 2023-12-11 09:22 UTC
Title says it all. Internal server error on get request.

**Comment by Stage4000** [comment] 2023-12-20 20:36
Same issue, if a token is provided it 500's, if it thinks no token is present it will return a JSON error to that effect.

**Comment by swiftyspiffy** [comment] 2023-12-21 01:41
taking a look

**Comment by Stage4000** [comment] 2023-12-21 02:44
I just took a quick glance at the code and it looks to me like $args is undefined on line 4.

**Comment by Stage4000** [comment] 2023-12-21 02:45
Maybe use count($_GET) == 1 instead of $args == 1
(I just looked at the refresh script so I may not fully understand how this script is called, just going off of the quick glance I took at it.)

**Comment by swiftyspiffy** [comment] 2023-12-21 04:03
See if it works now. The issue is that the refresh API was designed to be used with tokens generated using the create API (ie the API Client ID). It'll now attempt refreshing with the frontend Client ID if the API Client ID fails.

**Comment by Stage4000** [comment] 2023-12-21 21:15
Working on my end

**Comment by swiftyspiffy** [comment] 2023-12-21 23:13
💯. will close this, feel free to leave a comment if its still broken. also pls dont hammer the refresh endpoint :)

**Closed as completed by swiftyspiffy** 2023-12-21 23:13 UTC
